version: '3.8'

services:
  asesorias-api:
    image: ${DOCKER_USERNAME:-tu_usuario_docker}/asesorias-api:latest
    build:
      context: ./asesorias-api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=${MONGO_URI_API}
      - PORT=4000

  proyecto-microservicio:
    image: ${DOCKER_USERNAME:-tu_usuario_docker}/proyecto-microservicio:latest
    build:
      context: ./proyecto-microservicio
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      - MONGO_URI=${MONGO_URI_MICROSERVICIO}
      - PORT=4001
